### ISSUE TITLE
Mac (ARM) Release?

### ISSUE THREAD

**Issue by wwerkk** [samparkewolfe/RapidMax#7]
Is there any plans of updating this for ARM?

**Comment by jeppius** [comment]
Yep! I should really need it too...any plans? Did you manage to get it?

**Comment by wwerkk** [comment]
I assume this repo is no longer maintained, you can give this min-devkit version a try:
https://github.com/mzed/rapid/
I had some notarization issues when building it with VSCode, but with command line/XCode it works all fine.
Enjoy!

**Comment by jeppius** [comment]
Many thanks, it worked fine!
